config/routes.rb
Rails.application.routes.draw do
  get 'events/near' => 'events#near'
  get 'events/voted' => 'events#voted'
  get 'logout' => 'users#logout'
  get 'current_user_data/:id' => 'users#get_user_data'
  get 'user_search' => 'users#search'
  get 'users/current-user-info' => 'users#info'
  get 'auth' => 'users#instragram_signin'
  get 'get_instagram_token' => 'users#get_instagram_token'
  post 'set_instagram_token' => 'users#set_instagram_token'

  resources :events do
    resources :votes
    resources :remarks do
      resources :votes, only: :create
    end
  end

  resources :users

  root 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :votes, as: :votable, dependent: :destroy
  has_many :remarks, dependent: :destroy
  has_many :users, through: :votes
  validates_uniqueness_of :lat, scope: [:lng, :venue_name, :is_active], if: :is_active

  def self.near(bound, user)
    where("lat < ? and lat > ? and lng < ? and lng > ? and is_active = true and threshold <= ?", bound["maxlat"].to_f, bound["minlat"].to_f, bound["maxlng"].to_f, bound["minlng"].to_f, user.popularity).order(score: :desc).limit(25)
  end

  def self.end_all_active_events
    self.where(is_active: true).each do |event|
      event.end
    end
  end

  def attendees
    self.votes.where(vote_direction: 1).map {|vote| vote.user}
  end

  def end
    self.calculate_popularity
    self.is_active = false
    self.save
  end

  def most_pop_user
    self.users.order(:popularity).last
  end

  def calculate_popularity
    positive_votes = self.votes.where(vote_direction: 1)
    num_of_attendees = positive_votes.count
    attendees = positive_votes.map {|vote| vote.user}

    popularity_array = attendees.map {|attendee| attendee.popularity}
    popularity_of_most_popular = popularity_array.max

    dissers = self.votes.where(vote_direction: -1).map {|vote| vote.user}

    if positive_votes.count > 9 && self.score > 0
      ninetieth_percentile = (num_of_attendees * 0.1).to_i
      eightieth_percentile = (num_of_attendees * 0.2).to_i
      seventieth_percentile = (num_of_attendees * 0.3).to_i
      sixtieth_percentile = (num_of_attendees * 0.4).to_i
      fiftieth_percentile = (num_of_attendees * 0.5).to_i

      attendees[0].popularity += (self.score * 0.1)
      attendees[1..ninetieth_percentile].each {|u| u.popularity += (self.score * 0.08).to_i}
      attendees[(ninetieth_percentile + 1)..eightieth_percentile].each {|u| u.popularity += (self.score * 0.07).to_i}
      attendees[(eightieth_percentile + 1)..seventieth_percentile].each {|u| u.popularity += (self.score * 0.06).to_i}
      attendees[(seventieth_percentile + 1)..sixtieth_percentile].each {|u| u.popularity += (self.score * 0.05).to_i}
      attendees[(sixtieth_percentile + 1)..fiftieth_percentile].each {|u| u.popularity += (self.score * 0.04).to_i}
      attendees[(fiftieth_percentile + 1)..-1].each {|u| u.popularity += (self.score * 0.03).to_i}

    elsif positive_votes.count > 2 && self.score > 0
      attendees.each {|u| u.popularity += (popularity_of_most_popular * 0.1).to_i}

    else
      attendees.each {|attendee| attendee.popularity = (attendee.popularity * 0.9).to_i}
      dissers.each {|disser| disser.popularity += (popularity_of_most_popular * 0.1).to_i}

      dissers.each {|u| u.save}
    end

    attendees.each {|u| u.save}
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  protect_from_forgery :except => [:create]
  def index
  end

  def show
    @event = Event.find_by(id: params[:id])
    if current_user.voted_for?(@event)
      render "show"
    elsif with_in_range?(@event)
      render "show"
    else
      redirect_to root_path, flash: {alert: "Event is out of range"}
    end
  end

  def new
  end

  def create
    event = Event.new(permitted_params)
    if with_in_range?(event)
      if event.save
        Vote.create(user: current_user, votable: event, vote_direction: 1)
        render json: event.to_json
      else
        render :nothing => true, status: 422
      end
    else
      redirect_to root_path
    end
  end

  def near
    events = Event.near(params[:bound], current_user)
    render json: events.to_json
  end

  def voted
    events = current_user.voted_events
    render json: events.to_json
  end

  private
  def permitted_params
    params.require(:event).permit(:lat, :lng, :address, :venue_name, :place_id, :description, :house_party, :threshold, :url)
  end

  def with_in_range?(event)
    if params[:current_location]
      current_lat = params[:current_location][:lat].to_f
      current_lng = params[:current_location][:lng].to_f
      lat_diff = (event.lat - current_lat).abs
      lng_diff = (event.lng - current_lng).abs
      if lat_diff < 0.002 && lng_diff < 0.002
        return true
      end
    end
    false
  end

end

app/views/events/_attendee.html.erb
<div class="row user_row">
  <%= link_to user_path(user) do%>
  <div class="small-3 large-3 columns user_info">
    <%= image_tag(user.profile_pic_url) %>
    <!-- I'd move the p out of the ice cream and do  <%= user.popularity %>p  -->
    <%= user.first_name %> <%= user.popularity.to_s + "p"%>
  </div>
  <% end %>
  <% if user.id != current_user.id %>
  <div class="small-3 large-3 columns remark_buttons">  
    <%= link_to "hate", new_event_remark_path(event), data:{direction: -1}, class: "hate" %>
    <%= link_to "love", new_event_remark_path(event), data:{direction: 1}, class: "love"  %>
  </div>
  <% else %>
    <span class="small-6 columns centered"> beautiful you</span>
  <% end %>  
  <div class="small-3 large-3 columns love_form">
    <%= render partial: "remark_form", locals: { event: event, user: user, message: "tell em how you feel", val: 1 } %>
  </div>
  
  <div class="small-3 large-3 columns hate_form">
    <%= render partial: "remark_form", locals: { event: event, user: user, message: "feel my wrath", val: -1 } %>
  </div>

</div>

app/views/events/_event.html.erb
<div>
  <div class="event-name" data-lat="<%= event.lat %>" data-lng="<%= event.lng %>">
    <%= event.venue_name %>
  </div>
</div>

app/views/events/_new_event.html.erb
<%= form_for event do |f| %>
  <h2><%= event.venue_name %></h2>
  <p><%= event.address %></p>
  <%= f.text_field :lat, value: place.geometry.location.lat %>
  <%= f.text_field :lng, value: place.geometry.location.lng %>
  <%= f.text_field :address, value: place.vicinity %>
  <%= f.text_field :venue_name, value: place.name %>
  <%= f.number_field :score, value: current_user.popularity %>
  <%= f.submit %>
<% end %>

app/views/events/_remark.html.erb
<a href="#" <%="data-reveal-id=modal#{remark.id}"%>>
  <div class="remark small-12 columns">
    <%= image_tag(remark.giver.profile_pic_url)%>
    <% if remark.remark_direction == 1 %>
      <%= " showed   " %> <i class="fi-heart red"></i> <%= "  to " %>
    <% else %>
      <%= " threw " %> <i class="fi-skull black"></i> <%= "  at " %>
    <% end %>
    <%= image_tag(remark.receiver.profile_pic_url)%>
    <span class="small-12 columns descrip_text"><%= remark.description %></span>
  </div>
</a>

<div <%="id=modal#{remark.id}"%> class="reveal-modal <%= remark.remark_direction == 1 ? "love" : "hate" %>" data-reveal>
  <p class="close_button">
  <a href="#" class="close-reveal-modal close_button">close</a>
  </p>
  <p class="small-4 columns"><%= image_tag(remark.giver.profile_pic_url)%></p>
    <p class="small-4 columns emotion">
    <% if remark.remark_direction == 1 %>
      <i class="fi-heart emotion"></i>
    <% else %>
      <i class="fi-skull emotion"></i>
    <% end %>
    </p>
  <p class="small-4 columns"><%= image_tag(remark.receiver.profile_pic_url)%></p>
  <div class="row description">
    <%= remark.description %>
  </div>
  <div class="row columns picture">
    <% if remark.photo %>
      <%= image_tag(remark.photo) %>
    <% end %>
  </div>

    <div class="row score">
      <%= remark.score %><i class="fi-star emotion"></i>
    </div>

  <% if current_user.id != remark.giver.id && !remark.already_has_vote_from(current_user) %>
    <div class="row remark_vote">
      <div class="yaas">
        <%= form_for [remark.event, remark, Vote.new], method: "POST", class: "small-6 columns" do |f| %>
        <%= f.hidden_field :vote_direction, value: "1" %>
        <%= f.submit "yaas" %>
        <% end %>
      </div>
      <div class="nahh">
        <%= form_for [remark.event, remark, Vote.new], method: "POST", class: "small-6 columns" do |f| %>
        <%= f.hidden_field :vote_direction, value: "-1" %>
        <%= f.submit "nahh" %>
        <% end %>
      </div>
    </div>
  <% end %>

</div>

app/views/events/_remark_form.html.erb
<!-- You probably don't need the explicit method post here -->
  <%= form_for [event, Remark.new], :html => { :multipart => true }, :remote => true, method: "post" do |f| %>
  <%= f.hidden_field :remark_direction, value: val %>
  <%= f.hidden_field :user_id, value: user.id %>
  <%= f.text_field :description %>
  <%= f.file_field :photo %>
  <%= f.submit message, id: "create_remark" %>
  <%= f.button "nevermind", name: "back" %>
  <% end %>

app/views/events/index.html.erb
<ng-view></ng-view>

app/views/events/new.html.erb
<div id="new-map"></div>
<div id="newEventList">
<h1 id="newEventListHeader">Where are you?</h1>
</div>

app/views/events/show.html.erb
<div class="refresh row">
  <%= image_tag("https://app.donorpath.org/img/refresh.gif") %>
</div>

<% if @event.url %>

  <div class="row" id="event_show" style="background-image: url('<%=@event.url%>');">
    <p class="small-12 columns name" ><%= @event.venue_name || "Unknown" %></p>
    <p class="small-12 columns address"><%= @event.address || "Event address unavailable."%></p>
    <p class="small-12 columns description"><%= @event.description || "No description available."%>
  </div>
<% else %>
  <div class="row" id="event_show">
    <p class="small-12 columns name" ><%= @event.venue_name || "PlaceHolder" %></p>
    <p class="small-12 columns address"><%= @event.address || "21 PlaceHolder St, New York, NY 10001"%></p>
    <p class="small-12 columns description"><%= @event.description || "No description available."%>
  </div>

<% end %>

<% if !current_user.voted_for?(@event) %>
<div class="vote row">

  <div class="small-12 large-4 columns vote_button">
    <%= form_for [@event, Vote.new], method: "POST" do |f| %>
    <%= f.hidden_field :vote_direction, value: "1" %>
    <%= f.submit "bumpin" %>
    <%  end %>
  </div>

  <div class="small-12 large-4 columns vote_button">
    <%= form_for [@event, Vote.new], method: "POST" do |f| %>
    <%= f.hidden_field :vote_direction, value: "-1" %>
    <%= f.submit "just sad" %>
    <%  end %>
  </div>

</div>

<% else %>

  <% if current_user.vote_direction_for(@event) == -1 %>
  <div class="voted neg" <%= "style='display:none'" %>>
    <span class="checked_in">ditched this</span>
  </div>
  <% else %>
  <div class="voted pos"<%= "style='display:none'" %>>
    <span class="checked_in">checked in</span>
  </div>

  <div class="attendees">
    <% if @event.users.count == 1 %>
      <span class="small-12 columns title centered"> Just you so far... </span>
    <% else %>
      <span class="small-12 columns title centered"> Who else is here? </span>
    <% end %>
    <% @event.attendees.each do |user| %>
      <%= render partial: "attendee", locals: { event: @event, user: user } %>
    <% end %>
  </div>

  <div class="most_popular row">
    <p><i class="fi-crown"></i></p>
    <span class="small-12 columns title centered"> Most Popular</span>
    <%= image_tag(@event.most_pop_user.profile_pic_url) %>
    <p><%= @event.most_pop_user.first_name %></p>
  </div>


  <div class="remarks top_margin">
    <% if @event.remarks.count < 1 %>
      <span class="remark_b title"> No chatter yet </span>
    <% else %>
      <span class="title"> What are they saying? </span>
    <% end %>
    <% @event.remarks.each do |remark| %>
      <%= render partial: "remark", locals: { event: @event, remark: remark } %>
    <% end %>
  </div>
  <% end %>

<% end %>
</div>